# start you can send false or true will we do it all
std_msgs/Bool start
---
std_msgs/Bool result
std_msgs/Int8 step
# result	= True : I can do mission success
#			= False: I can't do mission sucess
# step		= will return our step
